services:

  rtcstats-server:
    # https://github.com/Taukon/rtcstats-server
    image: taukon/rtcstats-server
    restart: ${RESTART_POLICY:-unless-stopped}
    env_file:
      - ./rtcstats/.env
      - ./rtcstats/rtcstats-server/.env
    networks:
      meet.jitsi:
        aliases:
            - rtcstats-server.meet.jitsi


  rtc-visualizer:
    # image source: https://github.com/Taukon/rtc-visualizer/tree/feat/nginx-proxy
    image: taukon/rtc-visualizer-nginx-proxy
    restart: ${RESTART_POLICY:-unless-stopped}
    volumes:
      - ./rtcstats/rtc-visualizer/.data:/rtc-visualizer/.data
    env_file:
      - ./rtcstats/.env
      - ./rtcstats/rtc-visualizer/.env
    networks:
      meet.jitsi:
        aliases:
            - rtc-visualizer.meet.jitsi
