services:

  rtcstats_server:
    # image source: https://github.com/Taukon/rtcstats-server/tree/feat/env-config-for-s3-dynamodb-endpoints
    image: taukon/rtcstats-server-s3-dynamodb-endpoints
    restart: ${RESTART_POLICY:-unless-stopped}
    # ports:
    #   - 3000:3000
    #   - 8095:8095
    env_file:
      - ./rtcstats/.env
      - ./rtcstats/rtcstats-server/.env
    networks:
      meet.jitsi:
        aliases:
            - rtcstats-server.meet.jitsi


  rtc_visualizer:
    # image source: https://github.com/Taukon/rtc-visualizer/tree/feat/env-vars-for-s3-dynamodb-endpoints-nginx
    # (only add Nginx proxy for the RTC Visualizer: https://github.com/Taukon/rtc-visualizer/tree/feat/nginx-proxy)
    image: taukon/rtc-visualizer-s3-dynamodb-endpoints-nginx
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - 8087:8087
    volumes:
      - ./rtcstats/rtc-visualizer/.data:/rtc-visualizer/.data
    env_file:
      - ./rtcstats/.env
      - ./rtcstats/rtc-visualizer/.env
    networks:
      meet.jitsi:
        aliases:
            - rtc-visualizer.meet.jitsi
